FROM debian:buster

RUN apt-get update -y && apt-get install -y certbot

# ---------------- build ------------------
# docker run -it --rm --name certbot -v ./test:/letsencrypt -v ./certs:/etc/letsencrypt cerbot bash
